config/routes.rb
Rails.application.routes.draw do

  resources :hospitals
  devise_for :users

  resources :posts

  get 'solutions/index'
  get 'solutions/show'

  root to: 'solutions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_one_attached :photo
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  scope :desc, -> { order("posts.created_at DESC") }
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_action :set_hospital, only: [:show, :edit, :update, :destroy]
  PER = 9

  # GET /hospitals
  # GET /hospitals.json
  def index
    @hospitals = Hospital.all
    @q = Hospital.ransack(params[:q])
    @result = @q.result.page(params[:page]).per(PER)

  end

  # GET /hospitals/1
  # GET /hospitals/1.json
  def show
  end

  # GET /hospitals/new
  def new
    @hospital = Hospital.new
  end

  # GET /hospitals/1/edit
  def edit
  end

  # POST /hospitals
  # POST /hospitals.json
  def create
    @hospital = Hospital.new(hospital_params)
    @user = current_user
    @hospital.user_id = @user.id

    respond_to do |format|
      if @hospital.save
        format.html { redirect_to @hospital, notice: 'Hospital was successfully created.' }
        format.json { render :show, status: :created, location: @hospital }
      else
        format.html { render :new }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hospitals/1
  # PATCH/PUT /hospitals/1.json
  def update
    respond_to do |format|
      if @hospital.update(hospital_params)
        format.html { redirect_to @hospital, notice: 'Hospital was successfully updated.' }
        format.json { render :show, status: :ok, location: @hospital }
      else
        format.html { render :edit }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hospitals/1
  # DELETE /hospitals/1.json
  def destroy
    @hospital.destroy
    respond_to do |format|
      format.html { redirect_to hospitals_url, notice: 'Hospital was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hospital
      @hospital = Hospital.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hospital_params
      params.require(:hospital).permit(:hospitalname, :prefe, :addr, :doctor, :kind, :period, :body, :purpose, :need, :proposal, :result, :photo)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @user = current_user
    @post.user_id = @user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  def index
    @posts = Post.all
    @hospitals = Hospital.all
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/views/hospitals/_form.html.erb
<%= form_with model: @hospital, :html => { multipart: true } do |form| %>
  <% if hospital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hospital.errors.count, "error") %>
      prohibited this hospital from being saved:</h2>

      <ul>
        <% hospital.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :写真%>
    <%= form.file_field :photo, class:"file-input" %>
  </div>
  <div class="field">
    <%= form.label :院名%>
    <%= form.text_field :hospitalname, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :住所（県）%>
    <%= form.collection_select(:prefe_eq, Prefecture.all, :name, :name, {prompt: "選択してください"}, {class: "form-control"}) %>

  </div>

  <div class="field">
    <%= form.label :住所（県以降） %>
    <%= form.text_area :addr, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :院長 %>
    <%= form.text_area :doctor, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :形態 %>
    <%= form.text_area :kind, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :概要 %>
    <%= form.text_area :body, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :実施期間 %>
    <%= form.date_field :period, class:"form-control" %>
  </div>
  <div class="field">
    <%= form.label :目的%>
    <%= form.text_area :purpose, class:"form-control"%>
  </div>

  <div class="field">
    <%= form.label :ニーズ %>
    <%= form.text_field :need, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :結果 %>
    <%= form.text_field :result, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :ホームページ %>
    <%= form.text_field :homepage, class:"form-control" %>
  </div>

  <div class="actions text-center m-3">
    <%= form.submit "投稿", :class =>"btn btn-success" %>
  </div>
<% end %>

app/views/hospitals/edit.html.erb
<h1>Editing Hospital</h1>

<%= render 'form', hospital: @hospital %>

<%= link_to 'Show', @hospital %> |
<%= link_to 'Back', hospitals_path %>

app/views/hospitals/index.html.erb
<div class="container">
  <div class="related-articles text-center">
    <h3 class="title">最新の実績</h3>
    <legend></legend>
    <div class="container">
      <div class="row">
        <% @hospitals.first(3).each do |hospital| %>
          <div class="col-md-4">
            <a href="pkp">
              <% if hospital.photo.attached? %>
                <%= image_tag url_for(hospital.photo.variant(resize: "128x128")), class:"img-rounded img-responsive" %>
              <% end %>
            </a>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<hr>

  <%= search_form_for @q do |f| %>
    <div class="row px-3 justify-content-center">
      <div class="col-12 col-md-5">
        <div class="form-group">
          <%= f.label :kind_eq, "カテゴリーから絞り込み" %>
          <%= f.collection_select(:kind_eq, @hospitals, :kind, :kind, {prompt: "選択してください"}, {class: "form-control"}) %>
        </div>
      </div>
      <div class="col-12 col-md-5">
        <div class="form-group">
          <%= f.label :prefe_eq, "場所から絞り込み" %>
          <%= f.collection_select(:prefe_eq, Prefecture.all, :name, :name, {prompt: "選択してください"}, {class: "form-control"}) %>
        </div>
      </div>
      <div class="col-6 text-right">
        <div class="actions"><%= f.submit "検索", :class =>"btn btn-success btn-round" %></div>
      </div>
      <div class="col-6 text-left">
        <%= link_to "リセット", hospitals_path, class:"btn btn-success btn-round" %>
      </div>
    </div>
  <% end %>

<h3 class="title text-center">実績紹介</h3>
<div class="row p-3">
  <% @result.each do |hospital| %>
    <div class="col-md-4 col-sm-6">
      <div class="card card-blog bg-light">
        <div class="card-image text-center">
          <%= link_to hospital do %>
            <% if hospital.photo.attached? %>
              <%= image_tag url_for(hospital.photo.variant(resize: "128x128")), class:"img" %>
            <% end %>
          <% end %>
        </div>
        <div class="card-body text-center">
          <h4 class="card-title">
            <%= hospital.hospitalname %>
          </h4>
          <div class="card-description">
            <%= hospital.prefe %><%= hospital.addr %>
          </div>
          <hr>
          <div class="card-footer">
            <%= link_to "詳細", hospital_path(hospital), class:"btn btn-success" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<%= paginate @result %>

<%= link_to 'New Hospital', new_hospital_path %>

app/views/hospitals/new.html.erb
<div class="container">
  <h1>新規投稿</h1>

  <%= render 'form', hospital: @hospital %>

  <div class="col-12 text-center">
    <%= link_to 'Back', hospitals_path, class:"btn btn-danger m-3" %>
  </div>
</div>

app/views/hospitals/show.html.erb
<div class="section pb-0">
      <div class="container">
        <div class="row title-row">
          <div class="col-md-2">
            <h4 class="shop">実績</h4>
          </div>
          <div class="col-md-4 ml-auto">
            <div class="pull-right">
              <span class="text-muted">投稿日:<%= @hospital.created_at.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[@hospital.created_at.wday]})") %>:<label><%= @hospital.kind %></label></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-7 col-sm-6">
            <div class="ml-auto mr-auto">
              <% if @hospital.photo.attached? %>
              <%= image_tag url_for(@hospital.photo.variant(resize: "128x128")) %>
            <% end %>
            </div>
            <!-- end carousel -->
          </div>
          <div class="col-md-5 col-sm-6">
            <h2><%= @hospital.hospitalname %></h2>
            <h4 class="price"><strong><%= @hospital.prefe %><%= @hospital.addr %></strong></h4>
            <hr>
            <h5>院長</h5><p><%= @hospital.doctor %>
            <hr>
            <h5>目的</h5>
            <p><%= @hospital.body %></p>
            <div class="row">
              <div class="col-md-12 col-sm-12">
                <label>施工期間</label>
                <p><%= @hospital.period %></p>
              </div>
            </div>
            <hr>
          </div>
        </div>
      </div>
    </div>
    <hr>
<div class="section pt-0">
      <div class="container">
        <div class="faq">
          <h4>フロー</h4>
          <br>
          <div id="acordeon">
            <div id="accordion" role="tablist" aria-multiselectable="true">
              <div class="card no-transition">
                <div class="card-header card-collapse" role="tab" id="headingOne">
                  <h5 class="mb-0 panel-title">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">ニーズ</a>
                  </h5>
                </div>
                <div id="collapseOne" class="collapse" role="tabpanel" aria-labelledby="headingOne">
                  <div class="card-body"><%= @hospital.need %></div>
                </div>
                <div class="card-header card-collapse" role="tab" id="headingTwo">
                  <h5 class="mb-0 panel-title">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">提案</a>
                  </h5>
                </div>
                <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo">
                <div class="card-body"></div>
                <%= @hospital.purpose %>
                </div>
                <div class="card-header card-collapse" role="tab" id="headingThree">
                  <h5 class="mb-0 panel-title">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">結果</a>
                  </h5>
                </div>
                <div id="collapseThree" class="collapse" role="tabpanel" aria-labelledby="headingThree">
                  <div class="card-body"><%= @hospital.result %></div>
                </div>
              </div>
            </div>
            <!--  end acordeon -->
          </div>
        </div>
      </div>
    </div>
<%= link_to 'Edit', edit_hospital_path(@hospital) %> |
<%= link_to 'Back', hospitals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>b-solution</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.ico') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column" style="min-height: 100vh">
    <div class="menu-container bg-transparent">
      <div class="menu">
        <ul>
          <li class="logo"> <%= link_to image_tag('logo1.png', width:"300", height: "80", class: "logo"), root_path, style:"padding:0px;" %></li>
          <li><%= link_to "コンセプト", root_path %>
          </li>
          <li> <%= link_to "事業内容" ,page_path('jigyou') %>
          </li>
          <li><%= link_to '実績', hospitals_path %>
          </li>
          <li><%= link_to '会社概要',page_path('about') %>
          </li>
          <li><a href="https://recruitment.b-light-group.co.jp/">採用情報</a>
          </li>
          <li>
            <% if user_signed_in? %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "ログイン", new_user_session_path %>
          <% end %>
          </li>
        </ul>
      </div>
    </div>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="pt-4 p-3 p-md-5 px-auto">
      <div class="row justify-content-center">
        <div class="col-12 col-lg-3 text-center">
          <%= image_tag "logo2.png", width: "300", class: "mb-2" %>
          <small class="d-block mb-3 text-center">Copyright © B-Light-Group Inc. All Rights Reserved.</small>
        </div>
        <div class="col-6 col-md-2">
          <h5>企業情報</h5>
          <ul class="list-unstyled text-small">
            <li><a href="https://b-light-group.co.jp/message.html">コーポレートメッセージ</a></li>
            <li><a href="https://b-light-group.co.jp/b-light-group.html">ビーライトグループとは</a></li>
            <li><a href="about.html">会社概要</a></li>
            <li><a href="https://b-light-group.co.jp/location.html">事業所一覧</a></li>
            <li><a href="contact.html">お問い合わせ</a></li>
          </ul>
        </div>
        <div class="col-6 col-md-3">
          <h5>グループ会社</h5>
          <ul class="list-unstyled text-small">
            <li><a href="https://b-light-group.co.jp">株式会社ビーライトグループ</a></li>
            <li><a href="http://b-light.co.jp/">株式会社ビーライト</a></li>
            <li><a href="https://b-light-neo.co.jp">株式会社ビーライトネオ</a></li>
            <li><a href="https://b-solar.jp">株式会社ビーライトソーラー</a></li>
            <li><a href="https://b-premium.co.jp">株式会社ビーライトプレミアム</a></li>
            <li><a href="http://solutions.b-light.co.jp/">株式会社ビーライトソリューションズ</a></li>
          </ul>
        </div>
        <div class="col-6 col-md-2">
          <h5>事業案内</h5>
          <ul class="list-unstyled text-small">
            <li><a href="http://b-light.co.jp/construction.html">設備工事・設計施工事業</a></li>
            <li><a href="https://b-light-neo.co.jp/aliance.html">アライアンス事業</a></li>
            <li><a href="https://b-light-neo.co.jp/o_m.html">再生エネルギーO&M事業</a></li>
            <li><a href="https://b-premium.co.jp#develop">ランドシステム事業</a></li>
            <li><a href="https://b-renovation.co.jp">住宅再生事業</a></li>
            <li><a href="https://b-solar.jp">メンテナンス事業</a></li>
            <li class="none">医療コンサルティング事業</li>
          </ul>
        </div>
        <div class="col-6 col-md-2">
          <h5>採用情報</h5>
          <ul class="list-unstyled text-small">
            <li><a href="https://recruitment.b-light-group.co.jp/">新卒採用</a></li>
            <li class="none">中途採用</li>
            <li class="none">インターン・アルバイト</li>
            <li class="none">エントリーはこちら</li>
          </ul>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/pages/consulter1.html.erb
<div class="container">
  <h3>コンサルタント紹介</h3>
  <form>
    <div class="row">
      <div class="col-md-5 col-sm-5">
        <%= image_tag('', :class =>"img-thumbnail img-responsivea") %>
      </div>
      <div class="col-md-7 col-sm-7">
        <div class="form-group">
          <h6>名前</h6>
          <h6>あいうえお<h6>
        </div>
        <div class="form-group">
          <h6>職種</H6>
        </div>
        <div class="row price-row">
          <div class="col-md-6">
            <h6>誕生日</h6>
            <div class="input-group border-input"></div>
          </div>
          <div class="col-md-6">
            <h6>血液型</h6>
            <div class="input-group border-input"></div>
          </div>
        </div>
      </div>
    </div>
    <hr>
    <div class="col-12">
      <h6>経歴</h6><br>
      <p></p>
    </div>
    <hr>
    <div class="col-12">
      <h6>メッセージ</h6><br>
      <p></p>
    </div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>


<main class="role">
<div class="row">
  <div class="col-md-12 col-md text-center">
    <div class="row text-center justify-content-center mb-3 py-3">
      <h1 class="col-8 text-center">お知らせ一覧</h1></div>
    <div class="container justify-content-center bg-light pt-5">
      <table class="table mb-0">
        <tbody>
          <% @posts.each do |post| %>
            <% if user_signed_in? %>
              <tr>
                <td class="h4 font-weight-bold"><%= post.created_at.strftime("%Y年%m月%d日")%><br> <%= link_to post.title, post %></td>
                <td class="h4"><%= link_to '編集', edit_post_path(post) %>  <%= link_to '削除', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% else %>
              <tr>
                <td class="h4 font-weight-bold"><%= post.created_at.strftime("%Y年%m月%d日") %><br> <%= link_to post.title, post %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</main>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<main role="main" class="border-top">
<div class="container justify-content-center bg-light pt-5 ">
  <div class="col-md-8 offset-md-2 py-2">

    <h3><%= @post.title %></h2>
    <div class="text-right"><%= @post.created_at.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[@post.created_at.wday]})") %></div>
    <div class="detailText px-3 my-3">
      <%= @post.body %>
    </div>
  </div>
</div>

</main>
<% if user_signed_in? %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %>
<% end %>

app/views/solutions/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-12 d-none d-lg-block px-0">
      <div class="card border-0 card-plain">
        <img class="card-img rounded-0" src="img/jumbtron.jpg" alt="カードの画像">
      </div>
    </div>
    <div class="col-12 d-lg-none px-0">
      <div class="card border-0">
        <img class="card-img rounded-0" src="img/res_jumbtron.jpg" alt="カードの画像">
      </div>
    </div>
  </div>

  <hr class="featurette-divider " id="concept">

  <div class="row text-center justify-content-center mb-5 py-5">
    <div class="col-12 col-xl-12 text-center fadein text-solution" >
      <h3>CONCEPT</h3>
      <h2>地域医療を支え、地域に貢献する</h2>
    </div>
    <div class="col-12 col-xl-6 fadein">
      <p>私達は、地域医療を支えるクリニックの戦略作りに参画し、医療技術の研鑽に努めてきた医師がも大元力を発揮できるようクリニック運営の参謀役を務めます。</p>
      <p>そして、日本の医学をグローバルというマーケットで地域に根づくクリニックの立ち上げ支援まで手がけてゆきます。</p>
    </div>
  </div>

  <hr class="featurette-divider " id="concept">

  <div class="row text-center justify-content-center py-3">
    <div class="col-12 col-xl-12 text-center fadein text-solution" >
      <h3>事業内容</h3>
    </div>
    <div class="col-12 col-xl-6 fadein">
      <h5><strong>総合医療コンサルティング</strong></h5>
    </div>
  </div>
  <div id="class" class="row justify-content-center mb-3 pt-5 marketing bg-white">
    <div class="col-4 justify-content-center">
      <div class="card bg-light">
        <div class="card-body">
          <h2 class="text-center text-solar">開業支援</h2>
          <hr class="featurette-divider">
          <p>資金調達、採用、機器販売はもちろん、最適な土地探しからサポートさせていただきます。</p>
        </div>
      </div>
    </div>
    <!-- /.col-lg-4 -->
    <div class="col-12 col-md-4 justify-content-center">
      <div class="card bg-light">
        <div class="card-body">
          <h2 class="text-center text-solar">医院運営・経営支援</h2>
          <hr class="featurette-divider">
          <p>医院を運営に必要不可欠なノウハウで医師の医業を快適に行えるよう、経営業のサポートをさせていただきます。</p>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12 text-center">
      <%= link_to "詳しく", page_path('jigyou'), class:"btn btn-success" %>
    </div>
  </div>
  <!-- /.col-lg-4 -->
</div>
<hr>
<div class="row pb-3">
  <h3 class="col-12 text-center">実績紹介</h3>
  <% @hospitals.first(3).each do |hospital| %>
    <div class="col-md-4 col-sm-6">
      <div class="card card-blog bg-light">
        <div class="card-image text-center">
          <%= link_to hospital do %>
            <% if hospital.photo.attached? %>
              <%= image_tag url_for(hospital.photo.variant(resize: "128x128")), class:"img" %>
            <% end %>
          <% end %>
        </div>
        <div class="card-body text-center">
          <h4 class="card-title">
            <%= hospital.hospitalname %>
          </h4>
          <div class="card-description">
            <%= hospital.kind %>
            <%= hospital.need %>
          </div>
          <div class="card-footer">
            <%= link_to "詳細", hospital_path(hospital), class:"btn btn-success" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="col-12 text-center">
    <%= link_to "一覧をみる", hospitals_path, class: "btn btn-outline-success" %>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-4 col-sm-6 ml-auto mr-auto">
    <div class="card card-profile card-plain">
      <div class="card-avatar border-white">
        <a href="#avatar">
          <img src="./assets/img/placeholder.jpg" alt="...">
        </a>
      </div>
      <div class="card-body">
        <h4 class="card-title">Anonymous Tim</h4>
        <h6 class="card-category">A private guy</h6>
        <p class="card-description">
        Hey there! Welcome to your user card. As you can see, it is already looking great. But if you want to tell us more about yourself by adding details in the settings page.
        </p>
      </div>
      <div class="card-footer text-center">
        <a href="#paper-kit" class="btn btn-icon btn-outline-success btn-border btn-round">詳細</a>
      </div>
    </div>
    <!-- end card -->
  </div>
  <div class="col-md-4 col-sm-6 ml-auto mr-auto">
    <div class="card card-profile card-plain">
      <div class="card-avatar border-white">
        <a href="#avatar">
          <img src="./assets/img/faces/joe-gardner-2.jpg" alt="...">
        </a>
      </div>
      <div class="card-body">
        <h4 class="card-title">Joe Gardner</h4>
        <h6 class="card-category">Artist and Music Composer</h6>
        <p class="card-description">
        Joe Garnder is one of the co-founders and drives the technical strategy of the platform, customer support and brand. Talk with Joe only interesting topics.
        </p>
      </div>
      <div class="card-footer text-center">
        <a href="#paper-kit" class="btn btn-icon btn-outline-success btn-border btn-round">詳細</a>
      </div>
    </div>
    <!-- end card -->
  </div>
</div>
<hr>
<div class="row mb-3">
  <div class="col-md-12 col-md text-center">
    <div class="row text-center justify-content-center mb-3 py-3">
      <h3 class="col-8 text-center">お知らせ一覧</h3></div>
    <div class="container justify-content-center pt-2">
      <table class="table mb-0">
        <tbody>
          <% @posts.each do |post| %>
            <% if user_signed_in? %>
              <tr>
                <td class="h5 font-weight-bold"><%= post.created_at.strftime("%Y年%m月%d日")%><%= link_to post.title, post %></td>
                <td class="h5"><%= link_to '編集', edit_post_path(post) %>  <%= link_to '削除', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% else %>
              <tr>
                <td class="h4 font-weight-bold"><%= post.created_at.strftime("%Y年%m月%d日") %><br> <%= link_to post.title, post %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      <div class="col-12 text-center">
        <%= link_to "一覧をみる", posts_path, class: "btn btn-outline-success" %>
      </div>
    </div>
  </div>
</div>

app/views/solutions/show.html.erb
<h1>Solutions#show</h1>
<p>Find me in app/views/solutions/show.html.erb</p>